### ISSUE TITLE
How to set custom typeface for the label and buttons separately

### ISSUE THREAD

**Issue by sharathyadhav1** [ahmadnajar10/fancyDialog#1]

**Comment by a-najar** [comment]
/* To change the the title font and body and content 
 you can use this methods */
 
 builder.setPositiveButtonFont("fonts/lato.ttf");
 builder.setNegativeButtonFont("fonts/lato.ttf");
 builder.setTitleFont("fonts/lato.ttf");
 builder.setSubTitleFont("fonts/lato.ttf");
builder.setBodyFont("fonts/lato.ttf");

**Comment by sharathyadhav1** [comment]
thanks for the support

**Comment by a-najar** [comment]
you are welcome 😍😍😍
