### ISSUE TITLE
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name =your.dialog.FancyAlertDialog$Builder)

### ISSUE THREAD

**Issue by carozhu** [ahmadnajar10/fancyDialog#10]
Hello:
i found that error sometimes.
FancyAlertDialog should implement Serializable.

**Comment by a-najar** [comment]
@carozhu thanks for helping in support i upload new version please try to use it if you face any problem send it to me thanks

**Comment by rayliverified** [comment]
Serializable does not support serialization of onClickListeners which results in a Null Error Exception when recreated from OnPause. #12 
My PR #13 should solve our issues with crashes. Please check :crossed_fingers:
