### ISSUE TITLE
And just in case can i place the button with gravity property and other thing is if have only positive button is it possible to place it gravity center

### ISSUE THREAD

**Issue by sharathyadhav1** [ahmadnajar10/fancyDialog#2]
<img width="363" alt="screen shot 2017-03-15 at 11 33 52 am" src="https://cloud.githubusercontent.com/assets/8912909/23938044/f7e623ca-0973-11e7-9c73-8fc8abc701f2.png">

**Comment by a-najar** [comment]
I Will Work on it

**Comment by sharathyadhav1** [comment]
The whole button section should be placed in the relative layout and if there is only positive button it should be placed in the center !!! hope u got it thanks

**Comment by a-najar** [comment]
@sharathyadhav1 Yes i got it thanks 👍

**Comment by a-najar** [comment]
@sharathyadhav1  my friend 
update first to this version compile 'com.geniusforapp.fancydialog:FancyDialog:0.0.4'
then you can find new method added to the dialog builder like this 
builder.setButtonsGravity(PanelGravity.CENTER)
