### ISSUE TITLE
OnNegativeClicked is not public

### ISSUE THREAD

**Issue by hojatm-huma** [ahmadnajar10/fancyDialog#21]
Hi!

Sounds you have forgotten to put public in front of OnNegativeClicked!

**Comment by MahdiFarzami** [comment]
yes i get this error too ! 
Error:(127, 59) error: OnNegativeClicked is not public in FancyAlertDialog; cannot be accessed from outside package

**Comment by amarilindra** [comment]
Guys, just copy .java and .xml file to your project and add public to interface OnNegativeClicked
Don't add dependency directly, it is creating manifest merge issues.

**Comment by a-najar** [comment]
@h4ppysmile its fixed no sorry for this mistake ;) please update to the new version
