### ISSUE TITLE
error: style attribute 'android:attr/dialogCornerRadius' not found.

### ISSUE THREAD

**Issue by superdiazzz** [ahmadnajar10/fancyDialog#26]
How to solve this? this only happened in version 1.0.2, but in my latest version like 0.1.4 there are no issue building.

**Comment by a-najar** [comment]
@superdiazzz Could you please be more clear about the issue and include some of the crash report or the exact error you

**Comment by superdiazzz** [comment]
The error occur when building, it shows like below
```
ERROR: Failed to resolve: com.geniusforapp.fancydialog:FancyDialog:1.0.2
Show in Project Structure dialog
Affected Modules: app
```
but when i change back to version 0.1.4, everything good

error dependency is here:     implementation 'com.geniusforapp.fancydialog:FancyDialog:1.0.2'
so at the end, i am back using oldest version

**Comment by a-najar** [comment]
@superdiazzz  could you please try the new version if it's appearing any more
