### ISSUE TITLE
TextViews Appear When Empty

### ISSUE THREAD

**Issue by rayliverified** [ahmadnajar10/fancyDialog#7]
Currently, all three text fields must be set and display even when empty. The appropriate behavior should be that the TextViews for Title, Subtitle, and Body only appear if they are set in the Builder.

PR #6 fixes this issue.

**Comment by rayliverified** [comment]
Thanks for the merge, look forward to the updated Gradle soon :D

**Comment by a-najar** [comment]
update is done thanks 😉
