### ISSUE TITLE
Crashes when Home or Recents button is pressed.

### ISSUE THREAD

**Issue by rayliverified** [ahmadnajar10/fancyDialog#8]
Library crashes with the following exception when the dialogue is enabled and the Home or Recent button is pressed. 

> java.lang.RuntimeException: Parcelable encountered IOException writing serializable object

**Comment by a-najar** [comment]
@searchy2  thanks 
compile 'com.geniusforapp.fancydialog:FancyDialog:0.0.6 
fixed please check this version

**Comment by rayliverified** [comment]
:raised_hand_with_fingers_splayed:  Nice, great work!

**Comment by a-najar** [comment]
thanks
